FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang cmake make

COPY . /minlzma
WORKDIR /minlzma/build
RUN cmake .. 
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /minlzma/build/minlzdec/minlzdec /minlzma/build/minlzdec/minlzdec